site_name: Beer & Pizza Night Wiki
theme:
  name: material
  logo: assets/beerandpizza.png
  #custom_dir: docs/overrides
  palette:
    scheme: preference
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs    
plugins: 
  - search